# Generated by Django 6.0.4 on 2026-05-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignment_resubmission_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='late_submission_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
